baseURL = "https://www.learn-cljs.com/"
languageCode = "en-us"
title = "Learn ClojureScript"
theme = "book"

disableKinds = ['taxonomy', 'taxonomyTerm']
pygmentsCodeFences = true

[params]
BookMenuBundle = "/menu"
BookSearch = false